/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RecallPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  useLegacySyntax: false,
  learningSteps: [1, 10],
  graduatingInterval: 1,
  easyInterval: 4,
  maximumInterval: 365,
  startingEase: 2.5,
  easyBonus: 1.3,
  intervalModifier: 1,
  hardIntervalModifier: 1.2,
  lapseIntervalModifier: 0.5,
  dailyNewCardsLimit: 20,
  dailyReviewLimit: 200,
  showContext: true,
  randomizeOrder: true,
  flashcardFolders: [],
  // Empty = scan all folders
  showAddFlashcardCommand: false,
  showHintHotkey: "h",
  showMemoHotkey: "m"
};

// src/data.ts
var DataManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.data = this.getDefaultData();
  }
  getDefaultData() {
    return {
      schedules: {},
      stats: {
        totalCards: 0,
        dueToday: 0,
        newToday: 0,
        reviewedToday: 0,
        streak: 0
      },
      settings: { ...DEFAULT_SETTINGS }
    };
  }
  async load() {
    const loaded = await this.plugin.loadData();
    if (loaded) {
      this.data = {
        ...this.getDefaultData(),
        ...loaded,
        settings: {
          ...DEFAULT_SETTINGS,
          ...loaded.settings
        }
      };
    }
  }
  async save() {
    await this.plugin.saveData(this.data);
  }
  // Settings
  getSettings() {
    return this.data.settings;
  }
  async updateSettings(settings) {
    this.data.settings = { ...this.data.settings, ...settings };
    await this.save();
  }
  // Schedules
  getSchedule(cardId) {
    return this.data.schedules[cardId] || null;
  }
  async saveSchedule(schedule) {
    this.data.schedules[schedule.cardId] = schedule;
    await this.save();
  }
  getAllSchedules() {
    return this.data.schedules;
  }
  // Stats
  getStats() {
    return this.data.stats;
  }
  async updateStats(updates) {
    this.data.stats = { ...this.data.stats, ...updates };
    await this.save();
  }
  async recordReview() {
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const stats = this.data.stats;
    if (stats.lastStudyDate) {
      const lastDate = new Date(stats.lastStudyDate);
      const todayDate = new Date(today);
      const diffDays = Math.floor(
        (todayDate.getTime() - lastDate.getTime()) / (1e3 * 60 * 60 * 24)
      );
      if (diffDays === 1) {
        stats.streak++;
      } else if (diffDays > 1) {
        stats.streak = 1;
      }
    } else {
      stats.streak = 1;
    }
    stats.reviewedToday++;
    stats.lastStudyDate = today;
    await this.save();
  }
  async resetDailyStats() {
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    if (this.data.stats.lastStudyDate !== today) {
      this.data.stats.reviewedToday = 0;
      this.data.stats.newToday = 0;
    }
    await this.save();
  }
  /**
   * Count cards due today
   */
  countDueCards() {
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    return Object.values(this.data.schedules).filter(
      (s) => s.dueDate <= today
    ).length;
  }
  /**
   * Get cards that are due for review
   */
  getDueCardIds() {
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    return Object.entries(this.data.schedules).filter(([_, schedule]) => schedule.dueDate <= today).map(([cardId, _]) => cardId);
  }
  /**
   * Check if a card is new (never reviewed)
   */
  isNewCard(cardId) {
    return !this.data.schedules[cardId];
  }
  /**
   * Clean up orphaned schedules (for deleted cards)
   */
  async cleanupOrphanedSchedules(validCardIds) {
    const orphaned = Object.keys(this.data.schedules).filter(
      (id) => !validCardIds.has(id)
    );
    if (orphaned.length > 0) {
      orphaned.forEach((id) => delete this.data.schedules[id]);
      await this.save();
    }
  }
};

// src/parser.ts
function parseFlashcards(content, file, settings) {
  const cards = [];
  const yamlCards = parseYamlStyleCards(content, file);
  cards.push(...yamlCards);
  if (settings.useLegacySyntax) {
    const legacyCards = parseLegacyCards(content, file);
    cards.push(...legacyCards);
  }
  return cards;
}
function parseYamlStyleCards(content, file) {
  const cards = [];
  const lines = content.split("\n");
  let currentCard = null;
  let currentField = null;
  let currentValue = [];
  let startLine = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (trimmed.startsWith("Q:")) {
      if (currentCard && currentField) {
        saveFieldValue(currentCard, currentField, currentValue);
        if (currentCard.question && currentCard.answer) {
          cards.push(finalizeCard(currentCard, file, startLine));
        }
      }
      currentCard = { type: "basic", tags: [] };
      currentField = "question";
      currentValue = [trimmed.substring(2).trim()];
      startLine = i + 1;
    } else if (trimmed.startsWith("A:") && currentCard) {
      saveFieldValue(currentCard, currentField, currentValue);
      currentField = "answer";
      currentValue = [trimmed.substring(2).trim()];
    } else if (trimmed.startsWith("Hint:") && currentCard) {
      saveFieldValue(currentCard, currentField, currentValue);
      currentField = "hint";
      currentValue = [trimmed.substring(5).trim()];
    } else if (trimmed.startsWith("Memo:") && currentCard) {
      saveFieldValue(currentCard, currentField, currentValue);
      currentField = "memo";
      currentValue = [trimmed.substring(5).trim()];
    } else if (trimmed.startsWith("Tags:") && currentCard) {
      saveFieldValue(currentCard, currentField, currentValue);
      currentField = "tags";
      currentValue = [trimmed.substring(5).trim()];
    } else if (trimmed === "---" && currentCard) {
      saveFieldValue(currentCard, currentField, currentValue);
      if (currentCard.question && currentCard.answer) {
        cards.push(finalizeCard(currentCard, file, startLine));
      }
      currentCard = null;
      currentField = null;
      currentValue = [];
    } else if (currentCard && currentField && trimmed !== "") {
      currentValue.push(line);
    }
  }
  if (currentCard && currentField) {
    saveFieldValue(currentCard, currentField, currentValue);
    if (currentCard.question && currentCard.answer) {
      cards.push(finalizeCard(currentCard, file, startLine));
    }
  }
  return cards;
}
function parseLegacyCards(content, file) {
  const cards = [];
  const lines = content.split("\n");
  let questionLines = [];
  let answerLines = [];
  let inAnswer = false;
  let startLine = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (trimmed === "?") {
      inAnswer = true;
    } else if (trimmed === "---" || trimmed.startsWith("#")) {
      if (questionLines.length > 0 && answerLines.length > 0) {
        cards.push({
          id: generateCardId(file.path, startLine),
          question: questionLines.join("\n").trim(),
          answer: answerLines.join("\n").trim(),
          tags: extractTagsFromContent(content),
          sourcePath: file.path,
          lineNumber: startLine,
          type: "basic"
        });
      }
      questionLines = [];
      answerLines = [];
      inAnswer = false;
      if (trimmed.startsWith("#")) {
        continue;
      }
    } else if (trimmed !== "") {
      if (inAnswer) {
        answerLines.push(line);
      } else {
        if (questionLines.length === 0) {
          startLine = i + 1;
        }
        questionLines.push(line);
      }
    }
  }
  if (questionLines.length > 0 && answerLines.length > 0) {
    cards.push({
      id: generateCardId(file.path, startLine),
      question: questionLines.join("\n").trim(),
      answer: answerLines.join("\n").trim(),
      tags: extractTagsFromContent(content),
      sourcePath: file.path,
      lineNumber: startLine,
      type: "basic"
    });
  }
  return cards;
}
function expandClozeCards(card) {
  const clozePattern = /\{\{c(\d+)::([^}]+)\}\}/g;
  const matches = [...card.question.matchAll(clozePattern)];
  if (matches.length === 0) {
    const answerMatches = [...card.answer.matchAll(clozePattern)];
    if (answerMatches.length === 0) {
      return [card];
    }
  }
  const allMatches = [
    ...card.question.matchAll(clozePattern),
    ...card.answer.matchAll(clozePattern)
  ];
  const indices = [...new Set(allMatches.map((m) => parseInt(m[1])))].sort();
  return indices.map((index) => ({
    ...card,
    id: `${card.id}-c${index}`,
    type: "cloze",
    clozeIndex: index
  }));
}
function renderClozeQuestion(card) {
  if (card.type !== "cloze" || card.clozeIndex === void 0) {
    return card.question;
  }
  const pattern = new RegExp(
    `\\{\\{c${card.clozeIndex}::([^}]+)\\}\\}`,
    "g"
  );
  let result = card.question.replace(pattern, "[...]");
  result = result.replace(/\{\{c\d+::([^}]+)\}\}/g, "$1");
  return result;
}
function renderClozeAnswer(card) {
  if (card.type !== "cloze" || card.clozeIndex === void 0) {
    return card.answer;
  }
  const pattern = new RegExp(
    `\\{\\{c${card.clozeIndex}::([^}]+)\\}\\}`,
    "g"
  );
  let result = card.answer.replace(pattern, "**$1**");
  result = result.replace(/\{\{c\d+::([^}]+)\}\}/g, "$1");
  return result;
}
function saveFieldValue(card, field, value) {
  if (!field || value.length === 0)
    return;
  const joinedValue = value.join("\n").trim();
  switch (field) {
    case "question":
      card.question = joinedValue;
      break;
    case "answer":
      card.answer = joinedValue;
      break;
    case "hint":
      card.hint = joinedValue;
      break;
    case "memo":
      card.memo = joinedValue;
      break;
    case "tags":
      card.tags = joinedValue.split(",").map((t) => t.trim());
      break;
  }
}
function finalizeCard(card, file, lineNumber) {
  const id = generateCardId(file.path, lineNumber);
  return {
    id,
    question: card.question || "",
    answer: card.answer || "",
    hint: card.hint,
    memo: card.memo,
    tags: card.tags || [],
    sourcePath: file.path,
    lineNumber,
    type: "basic"
  };
}
function generateCardId(filePath, lineNumber) {
  const hash = simpleHash(`${filePath}:${lineNumber}`);
  return `card-${hash}`;
}
function simpleHash(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash;
  }
  return Math.abs(hash).toString(16);
}
function extractTagsFromContent(content) {
  const tagPattern = /#[\w-]+/g;
  const matches = content.match(tagPattern);
  return matches ? [...new Set(matches)] : [];
}

// src/ReviewModal.ts
var import_obsidian = require("obsidian");

// src/sm2.ts
function calculateNextReview(schedule, response, settings) {
  const now = /* @__PURE__ */ new Date();
  const todayStr = now.toISOString().split("T")[0];
  if (!schedule) {
    return createNewSchedule(response, settings, todayStr);
  }
  return updateSchedule(schedule, response, settings, todayStr);
}
function createNewSchedule(response, settings, todayStr) {
  let interval;
  let ease = settings.startingEase;
  switch (response) {
    case "easy":
      interval = settings.easyInterval;
      ease = settings.startingEase + 0.15;
      break;
    case "good":
      interval = settings.graduatingInterval;
      break;
    case "hard":
      interval = 1;
      ease = settings.startingEase - 0.15;
      break;
  }
  interval = Math.min(interval, settings.maximumInterval);
  const dueDate = addDays(todayStr, interval);
  return {
    cardId: "",
    // Will be set by caller
    interval,
    ease: Math.max(1.3, ease),
    // Minimum ease is 1.3
    dueDate,
    repetitions: 1,
    lastReview: todayStr
  };
}
function updateSchedule(schedule, response, settings, todayStr) {
  let { interval, ease, repetitions } = schedule;
  switch (response) {
    case "easy":
      interval = Math.round(interval * ease * settings.easyBonus);
      ease += 0.15;
      repetitions++;
      break;
    case "good":
      interval = Math.round(interval * ease);
      repetitions++;
      break;
    case "hard":
      interval = Math.round(interval * settings.hardIntervalModifier);
      ease -= 0.15;
      break;
  }
  ease = Math.max(1.3, ease);
  interval = Math.max(1, interval);
  interval = Math.min(interval, settings.maximumInterval);
  interval = Math.round(interval * settings.intervalModifier);
  const dueDate = addDays(todayStr, interval);
  return {
    ...schedule,
    interval,
    ease,
    dueDate,
    repetitions,
    lastReview: todayStr
  };
}
function previewNextIntervals(schedule, settings) {
  const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  if (!schedule) {
    return {
      hard: 1,
      good: settings.graduatingInterval,
      easy: settings.easyInterval
    };
  }
  const { interval, ease } = schedule;
  return {
    hard: Math.max(1, Math.round(interval * settings.hardIntervalModifier)),
    good: Math.min(settings.maximumInterval, Math.round(interval * ease)),
    easy: Math.min(
      settings.maximumInterval,
      Math.round(interval * ease * settings.easyBonus)
    )
  };
}
function formatInterval(days) {
  if (days < 1)
    return "<1d";
  if (days === 1)
    return "1d";
  if (days < 30)
    return `${days}d`;
  if (days < 365) {
    const months = Math.round(days / 30);
    return `${months}mo`;
  }
  const years = (days / 365).toFixed(1);
  return `${years}y`;
}
function addDays(dateStr, days) {
  const date = new Date(dateStr);
  date.setDate(date.getDate() + days);
  return date.toISOString().split("T")[0];
}

// src/ReviewModal.ts
var ReviewModal = class extends import_obsidian.Modal {
  constructor(app, cards, dataManager, settings, onComplete) {
    super(app);
    this.currentIndex = 0;
    this.state = "question";
    this.cards = cards;
    this.dataManager = dataManager;
    this.settings = settings;
    this.onComplete = onComplete;
    this.component = new import_obsidian.Component();
  }
  onOpen() {
    this.component.load();
    this.modalEl.addClass("recall-review-modal");
    this.titleEl.setText("Recall Review");
    this.createHeader();
    this.cardContentEl = this.contentEl.createDiv("recall-content");
    this.buttonContainer = this.contentEl.createDiv("recall-buttons");
    this.registerHotkeys();
    if (this.cards.length > 0) {
      this.showCard();
    } else {
      this.showComplete();
    }
  }
  onClose() {
    this.component.unload();
    this.onComplete();
  }
  createHeader() {
    const header = this.contentEl.createDiv("recall-header");
    this.progressEl = header.createDiv("recall-progress");
    this.contextEl = header.createDiv("recall-context");
    const editBtn = header.createEl("button", { cls: "recall-edit-btn" });
    (0, import_obsidian.setIcon)(editBtn, "pencil");
    editBtn.setAttribute("aria-label", "Edit card");
    editBtn.onclick = () => this.editCurrentCard();
  }
  registerHotkeys() {
    this.scope.register([], "Space", (e) => {
      e.preventDefault();
      this.handleSpace();
    });
    this.scope.register([], "h", (e) => {
      var _a;
      e.preventDefault();
      if (this.state === "question" && ((_a = this.currentCard) == null ? void 0 : _a.hint)) {
        this.showHint();
      }
    });
    this.scope.register([], "m", (e) => {
      var _a;
      e.preventDefault();
      if ((this.state === "question" || this.state === "hint") && ((_a = this.currentCard) == null ? void 0 : _a.memo)) {
        this.showMemo();
      }
    });
    this.scope.register([], "1", () => this.submitResponse("hard"));
    this.scope.register([], "2", () => this.submitResponse("good"));
    this.scope.register([], "3", () => this.submitResponse("easy"));
  }
  get currentCard() {
    return this.cards[this.currentIndex] || null;
  }
  handleSpace() {
    var _a, _b, _c;
    switch (this.state) {
      case "question":
        if ((_a = this.currentCard) == null ? void 0 : _a.hint) {
          this.showHint();
        } else if ((_b = this.currentCard) == null ? void 0 : _b.memo) {
          this.showMemo();
        } else {
          this.showAnswer();
        }
        break;
      case "hint":
        if ((_c = this.currentCard) == null ? void 0 : _c.memo) {
          this.showMemo();
        } else {
          this.showAnswer();
        }
        break;
      case "memo":
        this.showAnswer();
        break;
      case "answer":
        this.submitResponse("good");
        break;
    }
  }
  showCard() {
    const card = this.currentCard;
    if (!card) {
      this.showComplete();
      return;
    }
    this.state = "question";
    this.updateProgress();
    this.updateContext(card);
    this.renderQuestion(card);
    this.renderQuestionButtons(card);
  }
  updateProgress() {
    const current = this.currentIndex + 1;
    const total = this.cards.length;
    this.progressEl.setText(`${current} / ${total}`);
  }
  updateContext(card) {
    var _a;
    if (this.settings.showContext) {
      const fileName = (_a = card.sourcePath.split("/").pop()) == null ? void 0 : _a.replace(".md", "");
      this.contextEl.setText(`${fileName} \u2022 Line ${card.lineNumber}`);
    } else {
      this.contextEl.setText("");
    }
  }
  async renderQuestion(card) {
    this.cardContentEl.empty();
    const questionDiv = this.cardContentEl.createDiv("recall-question");
    const questionText = card.type === "cloze" ? renderClozeQuestion(card) : card.question;
    await import_obsidian.MarkdownRenderer.render(
      this.app,
      questionText,
      questionDiv,
      card.sourcePath,
      this.component
    );
  }
  renderQuestionButtons(card) {
    this.buttonContainer.empty();
    const btnRow = this.buttonContainer.createDiv("recall-btn-row");
    if (card.hint) {
      const hintBtn = btnRow.createEl("button", {
        text: "Show Hint (H)",
        cls: "recall-btn recall-btn-hint"
      });
      hintBtn.onclick = () => this.showHint();
    }
    if (card.memo) {
      const memoBtn = btnRow.createEl("button", {
        text: "Show Memo (M)",
        cls: "recall-btn recall-btn-memo"
      });
      memoBtn.onclick = () => this.showMemo();
    }
    const answerBtn = btnRow.createEl("button", {
      text: "Show Answer (Space)",
      cls: "recall-btn recall-btn-answer"
    });
    answerBtn.onclick = () => this.showAnswer();
  }
  async showHint() {
    const card = this.currentCard;
    if (!(card == null ? void 0 : card.hint))
      return;
    this.state = "hint";
    const hintDiv = this.cardContentEl.createDiv("recall-hint");
    hintDiv.createEl("div", { text: "Hint", cls: "recall-section-label" });
    await import_obsidian.MarkdownRenderer.render(
      this.app,
      card.hint,
      hintDiv.createDiv("recall-hint-content"),
      card.sourcePath,
      this.component
    );
    this.buttonContainer.empty();
    const btnRow = this.buttonContainer.createDiv("recall-btn-row");
    if (card.memo) {
      const memoBtn = btnRow.createEl("button", {
        text: "Show Memo (M)",
        cls: "recall-btn recall-btn-memo"
      });
      memoBtn.onclick = () => this.showMemo();
    }
    const answerBtn = btnRow.createEl("button", {
      text: "Show Answer (Space)",
      cls: "recall-btn recall-btn-answer"
    });
    answerBtn.onclick = () => this.showAnswer();
  }
  async showMemo() {
    const card = this.currentCard;
    if (!(card == null ? void 0 : card.memo))
      return;
    this.state = "memo";
    const memoDiv = this.cardContentEl.createDiv("recall-memo");
    memoDiv.createEl("div", { text: "Memory Palace", cls: "recall-section-label" });
    await import_obsidian.MarkdownRenderer.render(
      this.app,
      card.memo,
      memoDiv.createDiv("recall-memo-content"),
      card.sourcePath,
      this.component
    );
    this.buttonContainer.empty();
    const btnRow = this.buttonContainer.createDiv("recall-btn-row");
    const answerBtn = btnRow.createEl("button", {
      text: "Show Answer (Space)",
      cls: "recall-btn recall-btn-answer"
    });
    answerBtn.onclick = () => this.showAnswer();
  }
  async showAnswer() {
    const card = this.currentCard;
    if (!card)
      return;
    this.state = "answer";
    const answerDiv = this.cardContentEl.createDiv("recall-answer");
    answerDiv.createEl("div", { text: "Answer", cls: "recall-section-label" });
    const answerText = card.type === "cloze" ? renderClozeAnswer(card) : card.answer;
    await import_obsidian.MarkdownRenderer.render(
      this.app,
      answerText,
      answerDiv.createDiv("recall-answer-content"),
      card.sourcePath,
      this.component
    );
    this.renderRatingButtons(card);
  }
  renderRatingButtons(card) {
    this.buttonContainer.empty();
    const schedule = this.dataManager.getSchedule(card.id);
    const intervals = previewNextIntervals(schedule, this.settings);
    const btnRow = this.buttonContainer.createDiv("recall-btn-row recall-rating-row");
    const hardBtn = btnRow.createEl("button", {
      cls: "recall-btn recall-btn-hard"
    });
    hardBtn.innerHTML = `<span>Hard</span><span class="recall-interval">${formatInterval(intervals.hard)}</span>`;
    hardBtn.onclick = () => this.submitResponse("hard");
    const goodBtn = btnRow.createEl("button", {
      cls: "recall-btn recall-btn-good"
    });
    goodBtn.innerHTML = `<span>Good</span><span class="recall-interval">${formatInterval(intervals.good)}</span>`;
    goodBtn.onclick = () => this.submitResponse("good");
    const easyBtn = btnRow.createEl("button", {
      cls: "recall-btn recall-btn-easy"
    });
    easyBtn.innerHTML = `<span>Easy</span><span class="recall-interval">${formatInterval(intervals.easy)}</span>`;
    easyBtn.onclick = () => this.submitResponse("easy");
    const hint = this.buttonContainer.createDiv("recall-keyboard-hint");
    hint.setText("Press 1 (Hard), 2 (Good), or 3 (Easy)");
  }
  async submitResponse(response) {
    if (this.state !== "answer")
      return;
    const card = this.currentCard;
    if (!card)
      return;
    const currentSchedule = this.dataManager.getSchedule(card.id);
    const newSchedule = calculateNextReview(
      currentSchedule,
      response,
      this.settings
    );
    newSchedule.cardId = card.id;
    await this.dataManager.saveSchedule(newSchedule);
    await this.dataManager.recordReview();
    this.currentIndex++;
    this.showCard();
  }
  async editCurrentCard() {
    const card = this.currentCard;
    if (!card)
      return;
    const file = this.app.vault.getAbstractFileByPath(card.sourcePath);
    if (!(file instanceof import_obsidian.TFile))
      return;
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (view) {
      const editor = view.editor;
      editor.setCursor({ line: card.lineNumber - 1, ch: 0 });
      editor.scrollIntoView(
        { from: { line: card.lineNumber - 1, ch: 0 }, to: { line: card.lineNumber - 1, ch: 0 } },
        true
      );
    }
    this.close();
  }
  showComplete() {
    this.cardContentEl.empty();
    this.buttonContainer.empty();
    this.progressEl.setText("Complete!");
    this.contextEl.setText("");
    const completeDiv = this.cardContentEl.createDiv("recall-complete");
    completeDiv.createEl("h2", { text: "Review Complete!" });
    const stats = this.dataManager.getStats();
    const statsDiv = completeDiv.createDiv("recall-complete-stats");
    statsDiv.createEl("p", { text: `Reviewed today: ${stats.reviewedToday}` });
    statsDiv.createEl("p", { text: `Current streak: ${stats.streak} days` });
    const closeBtn = completeDiv.createEl("button", {
      text: "Close",
      cls: "recall-btn recall-btn-close"
    });
    closeBtn.onclick = () => this.close();
  }
};

// src/StatsModal.ts
var import_obsidian2 = require("obsidian");
var StatsModal = class extends import_obsidian2.Modal {
  constructor(app, dataManager) {
    super(app);
    this.dataManager = dataManager;
  }
  onOpen() {
    this.titleEl.setText("Recall Statistics");
    this.modalEl.addClass("recall-stats-modal");
    const stats = this.dataManager.getStats();
    const schedules = this.dataManager.getAllSchedules();
    this.renderStats(stats, schedules);
  }
  renderStats(stats, schedules) {
    const { contentEl } = this;
    const todaySection = contentEl.createDiv("recall-stats-section");
    todaySection.createEl("h3", { text: "Today" });
    const todayGrid = todaySection.createDiv("recall-stats-grid");
    this.createStatCard(todayGrid, "Reviewed", stats.reviewedToday.toString());
    this.createStatCard(todayGrid, "Due", this.dataManager.countDueCards().toString());
    this.createStatCard(todayGrid, "Streak", `${stats.streak} days`);
    const cardsSection = contentEl.createDiv("recall-stats-section");
    cardsSection.createEl("h3", { text: "Cards" });
    const cardStats = this.calculateCardStats(schedules);
    const cardsGrid = cardsSection.createDiv("recall-stats-grid");
    this.createStatCard(cardsGrid, "Total Scheduled", cardStats.total.toString());
    this.createStatCard(cardsGrid, "Learning", cardStats.learning.toString());
    this.createStatCard(cardsGrid, "Review", cardStats.review.toString());
    this.createStatCard(cardsGrid, "Mature", cardStats.mature.toString());
    const upcomingSection = contentEl.createDiv("recall-stats-section");
    upcomingSection.createEl("h3", { text: "Upcoming" });
    const forecast = this.calculateForecast(schedules);
    const forecastDiv = upcomingSection.createDiv("recall-forecast");
    forecast.forEach(({ label, count }) => {
      const row = forecastDiv.createDiv("recall-forecast-row");
      row.createSpan({ text: label, cls: "recall-forecast-label" });
      row.createSpan({ text: count.toString(), cls: "recall-forecast-count" });
    });
  }
  createStatCard(container, label, value) {
    const card = container.createDiv("recall-stat-card");
    card.createDiv({ text: value, cls: "recall-stat-value" });
    card.createDiv({ text: label, cls: "recall-stat-label" });
  }
  calculateCardStats(schedules) {
    const cards = Object.values(schedules);
    return {
      total: cards.length,
      learning: cards.filter((c) => c.interval < 1).length,
      review: cards.filter((c) => c.interval >= 1 && c.interval < 21).length,
      mature: cards.filter((c) => c.interval >= 21).length
    };
  }
  calculateForecast(schedules) {
    const today = /* @__PURE__ */ new Date();
    const forecast = [];
    const todayStr = today.toISOString().split("T")[0];
    const dueToday = Object.values(schedules).filter(
      (s) => s.dueDate <= todayStr
    ).length;
    forecast.push({ label: "Today", count: dueToday });
    for (let i = 1; i <= 7; i++) {
      const date = new Date(today);
      date.setDate(date.getDate() + i);
      const dateStr = date.toISOString().split("T")[0];
      const dueOnDate = Object.values(schedules).filter(
        (s) => s.dueDate === dateStr
      ).length;
      const dayName = i === 1 ? "Tomorrow" : date.toLocaleDateString("en-US", { weekday: "short" });
      forecast.push({ label: dayName, count: dueOnDate });
    }
    return forecast;
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/SettingsTab.ts
var import_obsidian3 = require("obsidian");
var RecallSettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("recall-settings");
    containerEl.createEl("h2", { text: "Recall Settings" });
    containerEl.createEl("h3", { text: "Flashcard Sources" });
    new import_obsidian3.Setting(containerEl).setName("Flashcard folders").setDesc("Only scan these folders for flashcards (comma-separated, empty = all folders)").addText(
      (text) => text.setPlaceholder("Flashcards, Notes/Study").setValue(this.plugin.settings.flashcardFolders.join(", ")).onChange(async (value) => {
        this.plugin.settings.flashcardFolders = value.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Daily Limits" });
    new import_obsidian3.Setting(containerEl).setName("New cards per day").setDesc("Maximum new cards to introduce per day").addText(
      (text) => text.setPlaceholder("20").setValue(String(this.plugin.settings.dailyNewCardsLimit)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.dailyNewCardsLimit = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Reviews per day").setDesc("Maximum reviews per day").addText(
      (text) => text.setPlaceholder("200").setValue(String(this.plugin.settings.dailyReviewLimit)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.dailyReviewLimit = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "Display" });
    new import_obsidian3.Setting(containerEl).setName("Show context").setDesc("Show source file and line number during review").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showContext).onChange(async (value) => {
        this.plugin.settings.showContext = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Randomize order").setDesc("Shuffle the order of cards during review").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.randomizeOrder).onChange(async (value) => {
        this.plugin.settings.randomizeOrder = value;
        await this.plugin.saveSettings();
      })
    );
    const advancedDetails = containerEl.createEl("details", {
      cls: "recall-advanced-settings"
    });
    advancedDetails.createEl("summary", {
      text: "Advanced Settings",
      cls: "recall-advanced-summary"
    });
    const advancedContainer = advancedDetails.createDiv("recall-advanced-container");
    advancedContainer.createEl("h3", { text: "Card Syntax" });
    new import_obsidian3.Setting(advancedContainer).setName("Legacy syntax support").setDesc("Enable ? separator for cards (in addition to YAML-style Q:/A:)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useLegacySyntax).onChange(async (value) => {
        this.plugin.settings.useLegacySyntax = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(advancedContainer).setName('Show "Add Flashcard" command').setDesc("Enable the command to insert a flashcard template (requires reload)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showAddFlashcardCommand).onChange(async (value) => {
        this.plugin.settings.showAddFlashcardCommand = value;
        await this.plugin.saveSettings();
      })
    );
    advancedContainer.createEl("h3", { text: "SM-2 Algorithm" });
    advancedContainer.createEl("p", {
      text: "These settings control the spaced repetition algorithm. Only change if you understand the SM-2 algorithm.",
      cls: "setting-item-description recall-algorithm-warning"
    });
    new import_obsidian3.Setting(advancedContainer).setName("Graduating interval").setDesc("Days until first review after learning phase").addText(
      (text) => text.setPlaceholder("1").setValue(String(this.plugin.settings.graduatingInterval)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.graduatingInterval = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(advancedContainer).setName("Easy interval").setDesc("Days until first review when pressing Easy").addText(
      (text) => text.setPlaceholder("4").setValue(String(this.plugin.settings.easyInterval)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.easyInterval = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(advancedContainer).setName("Maximum interval").setDesc("Maximum days between reviews").addText(
      (text) => text.setPlaceholder("365").setValue(String(this.plugin.settings.maximumInterval)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maximumInterval = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(advancedContainer).setName("Starting ease").setDesc("Initial ease factor for new cards (min: 1.3)").addText(
      (text) => text.setPlaceholder("2.5").setValue(String(this.plugin.settings.startingEase)).onChange(async (value) => {
        const num = parseFloat(value);
        if (!isNaN(num) && num >= 1.3) {
          this.plugin.settings.startingEase = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(advancedContainer).setName("Easy bonus").setDesc("Multiplier applied when pressing Easy").addText(
      (text) => text.setPlaceholder("1.3").setValue(String(this.plugin.settings.easyBonus)).onChange(async (value) => {
        const num = parseFloat(value);
        if (!isNaN(num) && num >= 1) {
          this.plugin.settings.easyBonus = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(advancedContainer).setName("Interval modifier").setDesc("Global multiplier for all intervals").addText(
      (text) => text.setPlaceholder("1.0").setValue(String(this.plugin.settings.intervalModifier)).onChange(async (value) => {
        const num = parseFloat(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.intervalModifier = num;
          await this.plugin.saveSettings();
        }
      })
    );
    advancedContainer.createEl("h3", { text: "Keyboard Shortcuts" });
    new import_obsidian3.Setting(advancedContainer).setName("Show hint hotkey").setDesc("Key to reveal hint during review").addText(
      (text) => text.setPlaceholder("h").setValue(this.plugin.settings.showHintHotkey).onChange(async (value) => {
        if (value.length === 1) {
          this.plugin.settings.showHintHotkey = value.toLowerCase();
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(advancedContainer).setName("Show memo hotkey").setDesc("Key to reveal memo during review").addText(
      (text) => text.setPlaceholder("m").setValue(this.plugin.settings.showMemoHotkey).onChange(async (value) => {
        if (value.length === 1) {
          this.plugin.settings.showMemoHotkey = value.toLowerCase();
          await this.plugin.saveSettings();
        }
      })
    );
    advancedContainer.createEl("h3", { text: "Danger Zone" });
    new import_obsidian3.Setting(advancedContainer).setName("Reset to defaults").setDesc("Reset all settings to their default values").addButton(
      (button) => button.setButtonText("Reset").setWarning().onClick(async () => {
        this.plugin.settings = { ...DEFAULT_SETTINGS };
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/main.ts
var RecallPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    this.dataManager = new DataManager(this);
    await this.dataManager.load();
    this.settings = this.dataManager.getSettings();
    this.addSettingTab(new RecallSettingsTab(this.app, this));
    this.addRibbonIcon("brain", "Start Recall Review", () => {
      this.startReview();
    });
    this.addCommand({
      id: "start-review",
      name: "Start Review",
      callback: () => this.startReview(),
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "r" }]
    });
    this.addCommand({
      id: "review-current-file",
      name: "Review Current File",
      callback: () => this.reviewCurrentFile()
    });
    if (this.settings.showAddFlashcardCommand) {
      this.addCommand({
        id: "add-flashcard",
        name: "Add Flashcard",
        editorCallback: (editor) => {
          const template = `Q: 
A: 
Hint: 
Memo: 
Tags: `;
          editor.replaceSelection(template);
          const cursor = editor.getCursor();
          editor.setCursor({ line: cursor.line - 4, ch: 3 });
        }
      });
    }
    this.addCommand({
      id: "show-statistics",
      name: "Show Statistics",
      callback: () => this.showStats()
    });
    await this.dataManager.resetDailyStats();
    console.log("Recall plugin loaded");
  }
  onunload() {
    console.log("Recall plugin unloaded");
  }
  async saveSettings() {
    await this.dataManager.updateSettings(this.settings);
  }
  /**
   * Start review of all due cards
   */
  async startReview() {
    const cards = await this.collectDueCards();
    if (cards.length === 0) {
      new import_obsidian4.Notice("No cards due for review!");
      return;
    }
    if (this.settings.randomizeOrder) {
      this.shuffleArray(cards);
    }
    const limitedCards = this.applyLimits(cards);
    new ReviewModal(
      this.app,
      limitedCards,
      this.dataManager,
      this.settings,
      () => {
        new import_obsidian4.Notice(`Review session complete!`);
      }
    ).open();
  }
  /**
   * Review only cards from the current file
   */
  async reviewCurrentFile() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian4.Notice("No active file");
      return;
    }
    const cards = await this.parseFile(activeFile);
    if (cards.length === 0) {
      new import_obsidian4.Notice("No flashcards found in this file");
      return;
    }
    const dueCards = cards.filter((card) => {
      const schedule = this.dataManager.getSchedule(card.id);
      if (!schedule)
        return true;
      const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
      return schedule.dueDate <= today;
    });
    if (dueCards.length === 0) {
      new import_obsidian4.Notice("No cards due in this file");
      return;
    }
    if (this.settings.randomizeOrder) {
      this.shuffleArray(dueCards);
    }
    new ReviewModal(
      this.app,
      dueCards,
      this.dataManager,
      this.settings,
      () => {
        new import_obsidian4.Notice(`Review complete!`);
      }
    ).open();
  }
  /**
   * Show statistics modal
   */
  showStats() {
    new StatsModal(this.app, this.dataManager).open();
  }
  /**
   * Collect all cards that are due for review
   */
  async collectDueCards() {
    const allCards = [];
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const cards = await this.parseFile(file);
      allCards.push(...cards);
    }
    await this.dataManager.updateStats({ totalCards: allCards.length });
    const validIds = new Set(allCards.map((c) => c.id));
    await this.dataManager.cleanupOrphanedSchedules(validIds);
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const dueCards = allCards.filter((card) => {
      const schedule = this.dataManager.getSchedule(card.id);
      if (!schedule)
        return true;
      return schedule.dueDate <= today;
    });
    return dueCards;
  }
  /**
   * Check if file is in a flashcard folder
   */
  isInFlashcardFolder(file) {
    if (this.settings.flashcardFolders.length === 0) {
      return true;
    }
    return this.settings.flashcardFolders.some((folder) => {
      const normalizedFolder = folder.endsWith("/") ? folder : folder + "/";
      return file.path.startsWith(normalizedFolder) || file.path.startsWith(folder);
    });
  }
  /**
   * Parse flashcards from a single file
   */
  async parseFile(file) {
    if (!this.isInFlashcardFolder(file)) {
      return [];
    }
    const content = await this.app.vault.cachedRead(file);
    const basicCards = parseFlashcards(content, file, this.settings);
    const allCards = [];
    for (const card of basicCards) {
      const expanded = expandClozeCards(card);
      allCards.push(...expanded);
    }
    return allCards;
  }
  /**
   * Apply daily limits to card list
   */
  applyLimits(cards) {
    const stats = this.dataManager.getStats();
    const newCards = cards.filter((c) => this.dataManager.isNewCard(c.id));
    const reviewCards = cards.filter((c) => !this.dataManager.isNewCard(c.id));
    const newLimit = Math.max(0, this.settings.dailyNewCardsLimit - stats.newToday);
    const reviewLimit = Math.max(0, this.settings.dailyReviewLimit - stats.reviewedToday);
    const limitedNew = newCards.slice(0, newLimit);
    const limitedReview = reviewCards.slice(0, reviewLimit);
    return [...limitedNew, ...limitedReview];
  }
  /**
   * Fisher-Yates shuffle
   */
  shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
  }
};
