/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SwipeNavigationPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  sensitivity: 50,
  enabled: true,
  debugMode: false
};
var SWIPE_COOLDOWN = 300;
var MIN_DELTA_FOR_LOG = 10;

// src/SettingsTab.ts
var import_obsidian = require("obsidian");
var SwipeNavigationSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("swipe-navigation-settings");
    containerEl.createEl("h2", { text: "Swipe Navigation Settings" });
    new import_obsidian.Setting(containerEl).setName("Enable swipe navigation").setDesc("Turn on/off trackpad swipe gestures for navigation").addToggle((toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
      this.plugin.settings.enabled = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Swipe sensitivity").setDesc("Minimum swipe distance to trigger navigation (lower = more sensitive)").addSlider((slider) => slider.setLimits(20, 100, 10).setValue(this.plugin.settings.sensitivity).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.sensitivity = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Developer" });
    new import_obsidian.Setting(containerEl).setName("Debug mode").setDesc("Log wheel events and navigation to the developer console (Cmd+Opt+I)").addToggle((toggle) => toggle.setValue(this.plugin.settings.debugMode).onChange(async (value) => {
      this.plugin.settings.debugMode = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "How to use" });
    containerEl.createEl("p", {
      text: "Use two-finger swipe left/right on your trackpad to navigate back and forward through your note history."
    });
    containerEl.createEl("h3", { text: "Compatibility" });
    const compatList = containerEl.createEl("ul");
    compatList.addClass("swipe-navigation-compat-list");
    compatList.createEl("li", { text: "macOS Trackpad - Excellent support" });
    compatList.createEl("li", { text: "Windows Precision Touchpad - Good support" });
    compatList.createEl("li", { text: "Older Windows Trackpads - Limited support" });
    compatList.createEl("li", { text: "Desktop with mouse only - Not supported" });
  }
};

// src/main.ts
var NAVIGATION_COMMANDS = {
  back: "app:go-back",
  forward: "app:go-forward"
};
var SwipeNavigationPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.lastSwipeTime = 0;
    this.abortController = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SwipeNavigationSettingsTab(this.app, this));
    this.setupSwipeListener();
    this.log("Plugin loaded");
  }
  onunload() {
    var _a;
    (_a = this.abortController) == null ? void 0 : _a.abort();
    this.abortController = null;
    this.log("Plugin unloaded");
  }
  // === Swipe Detection ===
  setupSwipeListener() {
    var _a;
    (_a = this.abortController) == null ? void 0 : _a.abort();
    this.abortController = new AbortController();
    const { signal } = this.abortController;
    document.addEventListener("wheel", (event) => {
      this.handleWheelEvent(event);
    }, { signal, passive: true });
  }
  handleWheelEvent(event) {
    if (!this.settings.enabled) {
      return;
    }
    const horizontalDelta = event.deltaX;
    const verticalDelta = Math.abs(event.deltaY);
    if (this.settings.debugMode && (Math.abs(horizontalDelta) > MIN_DELTA_FOR_LOG || verticalDelta > MIN_DELTA_FOR_LOG)) {
      this.log("Wheel event:", {
        deltaX: horizontalDelta.toFixed(2),
        deltaY: event.deltaY.toFixed(2),
        threshold: this.settings.sensitivity
      });
    }
    if (verticalDelta > Math.abs(horizontalDelta)) {
      return;
    }
    const threshold = this.settings.sensitivity;
    if (horizontalDelta < -threshold) {
      this.navigate("back");
    } else if (horizontalDelta > threshold) {
      this.navigate("forward");
    }
  }
  // === Navigation ===
  navigate(direction) {
    if (!this.checkCooldown(direction)) {
      return;
    }
    this.lastSwipeTime = Date.now();
    const command = NAVIGATION_COMMANDS[direction];
    const success = this.app.commands.executeCommandById(command);
    if (success) {
      this.log(`Navigating ${direction.toUpperCase()}`);
    } else {
      this.logWarn(`Navigation ${direction} failed - command not found`);
      new import_obsidian2.Notice(`Swipe Navigation: Could not navigate ${direction}`);
    }
  }
  checkCooldown(direction) {
    const now = Date.now();
    const timeSinceLastSwipe = now - this.lastSwipeTime;
    if (timeSinceLastSwipe < SWIPE_COOLDOWN) {
      if (this.settings.debugMode) {
        this.log(`Navigate ${direction} blocked by cooldown (${timeSinceLastSwipe}ms < ${SWIPE_COOLDOWN}ms)`);
      }
      return false;
    }
    return true;
  }
  // === Utilities ===
  log(message, data) {
    console.log("[SwipeNavigation]", message, data != null ? data : "");
  }
  logWarn(message, data) {
    console.warn("[SwipeNavigation]", message, data != null ? data : "");
  }
  // === Settings Management ===
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
