/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SwipeNavigationPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  sensitivity: 50,
  enabled: true,
  debugMode: false
};
var SWIPE_COOLDOWN = 300;
var MIN_DELTA_FOR_LOG = 10;
var SWIPE_THRESHOLD_MULTIPLIER = 3;
var MIN_VELOCITY_TO_ACTIVATE = 25;

// src/SettingsTab.ts
var import_obsidian = require("obsidian");
var SwipeNavigationSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("swipe-navigation-settings");
    containerEl.createEl("h2", { text: "Swipe Navigation Settings" });
    new import_obsidian.Setting(containerEl).setName("Enable swipe navigation").setDesc("Turn on/off trackpad swipe gestures for navigation").addToggle((toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
      this.plugin.settings.enabled = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Swipe sensitivity").setDesc("Minimum swipe distance to trigger navigation (lower = more sensitive)").addSlider((slider) => slider.setLimits(20, 100, 10).setValue(this.plugin.settings.sensitivity).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.sensitivity = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Developer" });
    new import_obsidian.Setting(containerEl).setName("Debug mode").setDesc("Log wheel events and navigation to the developer console (Cmd+Opt+I)").addToggle((toggle) => toggle.setValue(this.plugin.settings.debugMode).onChange(async (value) => {
      this.plugin.settings.debugMode = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "How to use" });
    containerEl.createEl("p", {
      text: "Use two-finger swipe left/right on your trackpad to navigate back and forward through your note history."
    });
    containerEl.createEl("h3", { text: "Compatibility" });
    const compatList = containerEl.createEl("ul");
    compatList.addClass("swipe-navigation-compat-list");
    compatList.createEl("li", { text: "macOS Trackpad - Excellent support" });
    compatList.createEl("li", { text: "Windows Precision Touchpad - Good support" });
    compatList.createEl("li", { text: "Older Windows Trackpads - Limited support" });
    compatList.createEl("li", { text: "Desktop with mouse only - Not supported" });
  }
};

// src/main.ts
var NAVIGATION_COMMANDS = {
  back: "app:go-back",
  forward: "app:go-forward"
};
var SwipeNavigationPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.lastSwipeTime = 0;
    this.abortController = null;
    // Swipe state tracking
    this.accumulatedDelta = 0;
    this.currentDirection = null;
    this.swipeActive = false;
    // Only true if velocity threshold was met
    // Visual indicator elements
    this.indicatorLeft = null;
    this.indicatorRight = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SwipeNavigationSettingsTab(this.app, this));
    this.createIndicators();
    this.setupSwipeListener();
    this.log("Plugin loaded");
  }
  onunload() {
    var _a;
    (_a = this.abortController) == null ? void 0 : _a.abort();
    this.abortController = null;
    this.removeIndicators();
    this.log("Plugin unloaded");
  }
  // === Visual Indicators ===
  createIndicators() {
    this.indicatorLeft = document.body.createDiv({
      cls: "swipe-nav-indicator swipe-nav-indicator-left"
    });
    this.indicatorLeft.createDiv({ cls: "swipe-nav-indicator-arrow" });
    this.indicatorRight = document.body.createDiv({
      cls: "swipe-nav-indicator swipe-nav-indicator-right"
    });
    this.indicatorRight.createDiv({ cls: "swipe-nav-indicator-arrow" });
  }
  removeIndicators() {
    var _a, _b;
    (_a = this.indicatorLeft) == null ? void 0 : _a.remove();
    (_b = this.indicatorRight) == null ? void 0 : _b.remove();
    this.indicatorLeft = null;
    this.indicatorRight = null;
  }
  updateIndicator(direction, progress) {
    const indicator = direction === "back" ? this.indicatorLeft : this.indicatorRight;
    if (!indicator)
      return;
    const clampedProgress = Math.min(Math.max(progress, 0), 1);
    const width = clampedProgress * 60;
    indicator.style.width = `${width}px`;
    indicator.style.opacity = `${clampedProgress}`;
    const arrow = indicator.querySelector(".swipe-nav-indicator-arrow");
    if (arrow) {
      arrow.style.opacity = clampedProgress >= 1 ? "1" : "0";
    }
    indicator.classList.toggle("ready", clampedProgress >= 1);
  }
  resetIndicators() {
    if (this.indicatorLeft) {
      this.indicatorLeft.style.width = "0";
      this.indicatorLeft.style.opacity = "0";
      this.indicatorLeft.classList.remove("ready");
    }
    if (this.indicatorRight) {
      this.indicatorRight.style.width = "0";
      this.indicatorRight.style.opacity = "0";
      this.indicatorRight.classList.remove("ready");
    }
  }
  // === Swipe Detection ===
  setupSwipeListener() {
    var _a;
    (_a = this.abortController) == null ? void 0 : _a.abort();
    this.abortController = new AbortController();
    const { signal } = this.abortController;
    document.addEventListener("wheel", (event) => {
      this.handleWheelEvent(event);
    }, { signal, passive: true });
  }
  handleWheelEvent(event) {
    if (!this.settings.enabled) {
      return;
    }
    const horizontalDelta = event.deltaX;
    const verticalDelta = Math.abs(event.deltaY);
    if (this.settings.debugMode && (Math.abs(horizontalDelta) > MIN_DELTA_FOR_LOG || verticalDelta > MIN_DELTA_FOR_LOG)) {
      this.log("Wheel event:", {
        deltaX: horizontalDelta.toFixed(2),
        deltaY: event.deltaY.toFixed(2),
        accumulated: this.accumulatedDelta.toFixed(2),
        active: this.swipeActive
      });
    }
    if (verticalDelta > Math.abs(horizontalDelta)) {
      return;
    }
    if (Math.abs(horizontalDelta) < 1) {
      return;
    }
    if (!this.swipeActive) {
      if (Math.abs(horizontalDelta) >= MIN_VELOCITY_TO_ACTIVATE) {
        this.swipeActive = true;
        if (this.settings.debugMode) {
          this.log("Swipe activated (velocity threshold met)");
        }
      } else {
        return;
      }
    }
    this.accumulatedDelta += horizontalDelta;
    const newDirection = this.accumulatedDelta < 0 ? "back" : this.accumulatedDelta > 0 ? "forward" : null;
    if (this.currentDirection && newDirection && this.currentDirection !== newDirection) {
      this.resetSwipeState();
      this.swipeActive = true;
      this.accumulatedDelta = horizontalDelta;
    }
    this.currentDirection = newDirection;
    if (this.currentDirection && !this.canNavigate(this.currentDirection)) {
      return;
    }
    const threshold = this.settings.sensitivity * SWIPE_THRESHOLD_MULTIPLIER;
    const progress = Math.abs(this.accumulatedDelta) / threshold;
    if (this.currentDirection) {
      this.updateIndicator(this.currentDirection, progress);
    }
    if (progress >= 1 && this.currentDirection) {
      this.navigate(this.currentDirection);
      this.animateIndicatorReset();
      this.resetSwipeState();
    }
  }
  resetSwipeState() {
    this.accumulatedDelta = 0;
    this.currentDirection = null;
    this.swipeActive = false;
  }
  canNavigate(direction) {
    const leaf = this.app.workspace.activeLeaf;
    if (!(leaf == null ? void 0 : leaf.history)) {
      return true;
    }
    if (direction === "back") {
      return leaf.history.backHistory.length > 0;
    } else {
      return leaf.history.forwardHistory.length > 0;
    }
  }
  animateIndicatorReset() {
    var _a, _b;
    (_a = this.indicatorLeft) == null ? void 0 : _a.classList.add("animating");
    (_b = this.indicatorRight) == null ? void 0 : _b.classList.add("animating");
    this.resetIndicators();
    setTimeout(() => {
      var _a2, _b2;
      (_a2 = this.indicatorLeft) == null ? void 0 : _a2.classList.remove("animating");
      (_b2 = this.indicatorRight) == null ? void 0 : _b2.classList.remove("animating");
    }, 200);
  }
  // === Navigation ===
  navigate(direction) {
    if (!this.checkCooldown(direction)) {
      return;
    }
    this.lastSwipeTime = Date.now();
    const command = NAVIGATION_COMMANDS[direction];
    const success = this.app.commands.executeCommandById(command);
    if (success) {
      if (this.settings.debugMode) {
        this.log(`Navigating ${direction.toUpperCase()}`);
      }
    } else {
      this.logWarn(`Navigation ${direction} failed - command not found`);
      new import_obsidian2.Notice(`Swipe Navigation: Could not navigate ${direction}`);
    }
  }
  checkCooldown(direction) {
    const now = Date.now();
    const timeSinceLastSwipe = now - this.lastSwipeTime;
    if (timeSinceLastSwipe < SWIPE_COOLDOWN) {
      if (this.settings.debugMode) {
        this.log(`Navigate ${direction} blocked by cooldown (${timeSinceLastSwipe}ms < ${SWIPE_COOLDOWN}ms)`);
      }
      return false;
    }
    return true;
  }
  // === Utilities ===
  log(message, data) {
    console.log("[SwipeNavigation]", message, data != null ? data : "");
  }
  logWarn(message, data) {
    console.warn("[SwipeNavigation]", message, data != null ? data : "");
  }
  // === Settings Management ===
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
