/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CustomerTagSorterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var INVALID_FOLDER_CHARS = /[\\/:*?"<>|]/g;
function sanitizeFolderName(name) {
  if (!name || typeof name !== "string") {
    return null;
  }
  let sanitized = name.trim();
  if (sanitized.includes("..") || sanitized.startsWith("/") || sanitized.startsWith("\\")) {
    return null;
  }
  sanitized = sanitized.replace(INVALID_FOLDER_CHARS, "");
  if (!sanitized || sanitized.length === 0) {
    return null;
  }
  if (sanitized.length > 255) {
    sanitized = sanitized.substring(0, 255);
  }
  return sanitized;
}
var DEFAULT_SETTINGS = {
  sourceFolder: "Notes",
  targetFolder: "Customer",
  runOnStartup: true,
  propertyName: "Customer"
};
var CustomerTagSorterPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "sort-customer-files",
      name: "Sort files by Customer tag",
      callback: () => this.sortFilesByCustomer()
    });
    if (this.settings.runOnStartup) {
      this.app.workspace.onLayoutReady(() => {
        this.sortFilesByCustomer();
      });
    }
    this.addSettingTab(new CustomerTagSorterSettingTab(this.app, this));
  }
  async sortFilesByCustomer() {
    const { vault } = this.app;
    const sourceFolder = vault.getAbstractFileByPath(this.settings.sourceFolder);
    if (!sourceFolder || !(sourceFolder instanceof import_obsidian.TFolder)) {
      new import_obsidian.Notice(`Source folder "${this.settings.sourceFolder}" not found!`);
      return;
    }
    const targetParent = this.settings.targetFolder;
    if (targetParent && !vault.getAbstractFileByPath(targetParent)) {
      try {
        await vault.createFolder(targetParent);
        await new Promise((resolve) => setTimeout(resolve, 50));
      } catch (error) {
        console.error(`[CustomerTag] Failed to create target folder: ${targetParent}`, error);
        new import_obsidian.Notice(`Failed to create target folder "${targetParent}"`);
        return;
      }
    }
    let movedCount = 0;
    let skippedCount = 0;
    let errorCount = 0;
    const filesToProcess = [];
    for (const child of sourceFolder.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        filesToProcess.push(child);
      }
    }
    for (const file of filesToProcess) {
      const rawCustomer = this.getCustomerFromFrontmatter(file);
      if (rawCustomer) {
        const customer = sanitizeFolderName(rawCustomer);
        if (!customer) {
          console.warn(`[CustomerTag] Invalid customer name in ${file.path}: "${rawCustomer}"`);
          skippedCount++;
          continue;
        }
        const targetFolderPath = targetParent ? `${targetParent}/${customer}` : customer;
        try {
          let targetFolder = vault.getAbstractFileByPath(targetFolderPath);
          if (!targetFolder) {
            await vault.createFolder(targetFolderPath);
            await new Promise((resolve) => setTimeout(resolve, 50));
            targetFolder = vault.getAbstractFileByPath(targetFolderPath);
          }
          if (!targetFolder || !(targetFolder instanceof import_obsidian.TFolder)) {
            console.error(`[CustomerTag] Failed to create/access folder: ${targetFolderPath}`);
            errorCount++;
            continue;
          }
          const newPath = `${targetFolderPath}/${file.name}`;
          const existingFile = vault.getAbstractFileByPath(newPath);
          if (existingFile) {
            skippedCount++;
            continue;
          }
          await vault.rename(file, newPath);
          movedCount++;
        } catch (error) {
          console.error(`[CustomerTag] Error moving ${file.path}:`, error);
          errorCount++;
        }
      }
    }
    const messages = [];
    if (movedCount > 0)
      messages.push(`Moved ${movedCount} file(s)`);
    if (skippedCount > 0)
      messages.push(`Skipped ${skippedCount}`);
    if (errorCount > 0)
      messages.push(`Errors: ${errorCount}`);
    if (messages.length > 0) {
      new import_obsidian.Notice(messages.join(", "));
    } else {
      new import_obsidian.Notice("No files to move.");
    }
  }
  getCustomerFromFrontmatter(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    const propertyName = this.settings.propertyName;
    if ((cache == null ? void 0 : cache.frontmatter) && cache.frontmatter[propertyName]) {
      const value = cache.frontmatter[propertyName];
      if (typeof value === "string") {
        return value;
      }
      if (Array.isArray(value) && value.length > 0) {
        const firstValue = value[0];
        if (typeof firstValue === "string") {
          return firstValue;
        }
      }
    }
    return null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var CustomerTagSorterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Customer Tag Sorter Settings" });
    new import_obsidian.Setting(containerEl).setName("Source Folder").setDesc("The folder to scan for files with tags").addText(
      (text) => text.setPlaceholder("Notes").setValue(this.plugin.settings.sourceFolder).onChange(async (value) => {
        this.plugin.settings.sourceFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Target Folder").setDesc("Parent folder where subfolders will be created (e.g. 'Customer' creates Customer/ClientName)").addText(
      (text) => text.setPlaceholder("Customer").setValue(this.plugin.settings.targetFolder).onChange(async (value) => {
        this.plugin.settings.targetFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Property Name").setDesc("The frontmatter property to sort by (e.g. Customer, Project, Category)").addText(
      (text) => text.setPlaceholder("Customer").setValue(this.plugin.settings.propertyName).onChange(async (value) => {
        this.plugin.settings.propertyName = value || "Customer";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Run on Startup").setDesc("Automatically sort files when Obsidian starts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.runOnStartup).onChange(async (value) => {
        this.plugin.settings.runOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Manual Sort").setDesc("Manually trigger the sorting process").addButton(
      (button) => button.setButtonText("Sort Now").onClick(async () => {
        await this.plugin.sortFilesByCustomer();
      })
    );
  }
};
