/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CustomerTagSorterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  sourceFolder: "Notes",
  runOnStartup: true
};
var CustomerTagSorterPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "sort-customer-files",
      name: "Sort files by Customer tag",
      callback: () => this.sortFilesByCustomer()
    });
    if (this.settings.runOnStartup) {
      this.app.workspace.onLayoutReady(() => {
        this.sortFilesByCustomer();
      });
    }
    this.addSettingTab(new CustomerTagSorterSettingTab(this.app, this));
  }
  async sortFilesByCustomer() {
    const { vault } = this.app;
    const sourceFolder = vault.getAbstractFileByPath(this.settings.sourceFolder);
    if (!sourceFolder || !(sourceFolder instanceof import_obsidian.TFolder)) {
      new import_obsidian.Notice(`Source folder "${this.settings.sourceFolder}" not found!`);
      return;
    }
    let movedCount = 0;
    const filesToProcess = [];
    for (const child of sourceFolder.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        filesToProcess.push(child);
      }
    }
    for (const file of filesToProcess) {
      const customer = this.getCustomerFromFrontmatter(file);
      if (customer) {
        const targetFolderPath = customer;
        let targetFolder = vault.getAbstractFileByPath(targetFolderPath);
        if (!targetFolder) {
          await vault.createFolder(targetFolderPath);
          targetFolder = vault.getAbstractFileByPath(targetFolderPath);
        }
        if (targetFolder instanceof import_obsidian.TFolder) {
          const newPath = `${targetFolderPath}/${file.name}`;
          const existingFile = vault.getAbstractFileByPath(newPath);
          if (!existingFile) {
            await vault.rename(file, newPath);
            movedCount++;
          }
        }
      }
    }
    if (movedCount > 0) {
      new import_obsidian.Notice(`Moved ${movedCount} file(s) to customer folders.`);
    } else {
      new import_obsidian.Notice("No files to move.");
    }
  }
  getCustomerFromFrontmatter(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    if ((cache == null ? void 0 : cache.frontmatter) && cache.frontmatter["Customer"]) {
      return cache.frontmatter["Customer"];
    }
    return null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var CustomerTagSorterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Customer Tag Sorter Settings" });
    new import_obsidian.Setting(containerEl).setName("Source Folder").setDesc("The folder to scan for files with Customer tags").addText(
      (text) => text.setPlaceholder("Notes").setValue(this.plugin.settings.sourceFolder).onChange(async (value) => {
        this.plugin.settings.sourceFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Run on Startup").setDesc("Automatically sort files when Obsidian starts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.runOnStartup).onChange(async (value) => {
        this.plugin.settings.runOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Manual Sort").setDesc("Manually trigger the sorting process").addButton(
      (button) => button.setButtonText("Sort Now").onClick(async () => {
        await this.plugin.sortFilesByCustomer();
      })
    );
  }
};
